version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1337
    ports:
      - "3307:3307"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

